### PR TITLE
Feature:  Auto restore the previous session at startup, etc.

### LINKED ISSUE #9: Restore session after startup
Would be very handy, if this extension could save all windows before a system shutdown and restore them after startup, with the same window size and position (including workspaces).

### LINKED ISSUE #59: Dragging windows becomes choppy when the extension is enabled
The extension seems to be somehow impacting performance. The screencast doesn't record window movement for some reason. The only thing visible is during the last 3 seconds - showing how smooth window dragging is with the extension disabled. Otherwise window dragging is choppy and extremely delayed.

Occurs on: Pop!_OS 22.04 LTS | GNOME Shell 42.3.1

https://user-images.githubusercontent.com/59068073/189334804-581f939e-00f5-46d3-b7b9-edc2c4c7746e.mp4

### LINKED ISSUE #60: Save session periodically
Setup: 
 - I don't use multiple sessions, what I want is to be able to restart my pc and have everything restored, that's it.

Issue: 
 - I find myself clicking the "Save current session" multiple times during the day because it already happened a couple of times that I forgot to do that and the last used session was too old. 
 
 Proposal: 
  - Have the option to set periodical savings of the current session. e.g. every 5 minutes the current session gets saved. 
  - There are already propositions to save before the shutdown, but I suppose that won't be that easy also considering emergency shutdowns and this is a very simple fix for that. Normal shutdown or not, your sessions would be saved some time before the shutdown because it is saved periodically

### PR DESCRIPTION
**Pull request by nlpsuge**
Includes:
1. Periodically, save windows when windows / apps states are changed. (fixes #60)
2. Auto close and save apps and windows  while `Log Out/Restart/Power Off` (fixes #9)
3. Auto restore the previous session at startup (fixes #9)
4. New configurations in Preferences and rename
5. `Stash and restore ` under `Restore sessions ` is renamed to `Restore windows states after Gnome Shell restarts` and it will be disabled on Wayland.
6. More support for apps that launched via the command line. Now those apps states can also be restored.
7. Fixes #59

### CODE REVIEW

**Comment by nlpsuge** [comment]
> 2. Auto close and save apps and windows  while `Log Out/Restart/Power Off` (fixes [Restore session after startup #9](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/issues/9))

Enable this feature through `Auto close session` under `Close windows`:
image

After you click the `Log Out/Restart/Power Off` button:
`image

If the second button on the above dialog has `via AWSM`, it means this feature is enabled. 

After you click `Log Out(via AWSM)`, all apps and windows will be closed automatically by AWSM. But some apps might be still opening, you have to close them yourself; then if there are no running apps, this extension logs out the current user immediately.

**Comment by nlpsuge** [comment]
> 3. Auto restore the previous session at startup (fixes [Restore session after startup #9](https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/issues/9))

Here is the overview of `Restore sessions` settings:
image

Activate `Restore previous apps and windows at startup` to enable this feature. This option and `Restore selected session at startup` are exclusive. And this option works for shutting down the system normally (via Log Out/Restart/Power Off buttons) and other ways (like pressing the physical power-off button).

Then while startup, AWSM will read the previous saved session configs to launch and restore apps and states.

The session configs are saved in the path `~/.config/another-window-session-manager/sessions/currentSession`.

**Comment by EkanshdeepGupta** [comment]
Hey in which version is this update a part of? Is it pushed to extensions.gnome.org? I have the latest version from the GNOME store (how do I find out which version I have installed?) but I don't see the "Auto Close Session" option under the Close Windows tab of settings.

**Comment by nlpsuge** [comment]
> Hey in which version is this update a part of? Is it pushed to extensions.gnome.org? I have the latest version from the GNOME store (how do I find out which version I have installed?) but I don't see the "Auto Close Session" option under the Close Windows tab of settings.

No, I've not pushed it to extensions.gnome.org. This PR is work-in-progress. 

Two blocking issues remain:
* Currently, after all apps are closed the system will log out (or restart, shutdown) immediately, but the processes related to apps may not exit yet. For example, Microsoft Edge may opens with a `Microsoft Edge Closed Unexpectedly` dialog next time:

image


* Gnome Shell sometimes freezes after unlocking. But I can't sure it's caused by my extension...

**Comment by nlpsuge** [comment]
> > Hey in which version is this update a part of? Is it pushed to extensions.gnome.org? I have the latest version from the GNOME store (how do I find out which version I have installed?) but I don't see the "Auto Close Session" option under the Close Windows tab of settings.
> 
> No, I've not pushed it to extensions.gnome.org. This PR is work-in-progress.
> 
> Two blocking issues remain:
> 
>     * Currently, after all apps are closed the system will log out (or restart, shutdown) immediately, but the processes related to apps may not exit yet. For example, Microsoft Edge may opens with a `Microsoft Edge Closed Unexpectedly` dialog next time:
> 
> 
> image
> 
>     * Gnome Shell sometimes freezes after unlocking. But I can't sure it's caused by my extension...

The first issue has been fixed. The second not, I can't reproduce it myself, it probably happens occasionally.

**Pull request merged**
