### PR TITLE
Added a verbose logging toggle to debugging settings

### PR DESCRIPTION
**Pull request by Rambomst**
- Added a toggle to enable/disable verbose logging (info logs) to the Debugging settings area.

Let me know if you want anything changed.

### CODE REVIEW

**Comment by freddyw** [comment]
Nice one, would love to see this get merged!

**Comment by nlpsuge** [comment]
Sorry for the delay, I've been pretty busy in recent months.

I'm testing it and it should be merged soon. Thank you very much.

**Comment by Rambomst** [comment]
> Sorry for the delay, I've been pretty busy in recent months.
> 
> I'm testing it and it should be merged soon. Thank you very much.

All good, we all get busy :)

Let me know if there are any changes you want me to make or if you need me to test it on a specific version :)

**Comment by nlpsuge** [comment]
Hi @Rambomst, 

I made some fixes based on your branch (see: https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/commit/7c507a6efb86c2c6210960491e09271e0beb5254).

1) After modifying the `xxx.gschema.xml` file, run `glib-compile-schemas schemas/` under the project to generate a new `schemas/gschemas.cbompiled` file. Otherwise, the `Verbose logging` switch will not work.
2) I'd like to keep the spaces after `DEBUG`, `ERROR` and `INFO` because they have different lengths, which makes it easier to view and compare the logs with different levels during development.

Your code has been included in this PR: https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager/pull/113, which will be merged soon.

**Pull request merged**
